name: medic
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  #service
  dio: ^4.0.6
  freezed: ^2.3.4
  sms_autofill: ^2.3.0
  url_launcher: ^6.1.11
  flutter_vibrate: ^1.3.0
  flutter_riverpod: ^2.3.6
  shared_preferences: ^2.1.1
  proste_indexed_stack: ^0.2.4
  flutter_masked_text2: ^0.9.1
  currency_text_input_formatter: ^2.1.8

  #auth:
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.0
  google_sign_in: ^6.1.2
  sign_in_with_apple: ^4.3.0
  flutter_login_facebook: ^1.8.0

  #location:
  google_maps_flutter: ^2.3.0
  geolocator: ^9.0.2
  osm_nominatim: ^2.0.1

  #ui
  intl: ^0.18.0
  lottie: ^2.3.2
  shimmer: ^2.0.0
  swipe_deck: ^1.1.0
  flutter_svg: ^2.0.5
  measure_size: ^4.0.0
  google_fonts: ^4.0.4
  flutter_remix: ^0.0.3
  image_cropper: ^4.0.1
  image_picker: ^0.8.7+5
  flutter_slidable: ^3.0.0
  phone_form_field: ^7.1.0
  flutter_screenutil: ^5.8.2
  animated_rating_bar: ^0.0.8
  cached_network_image: ^3.2.3
  zoom_pinch_overlay: ^1.4.1+3
  smooth_page_indicator: ^1.1.0
  flutter_native_splash: ^2.3.0
  top_snackbar_flutter: ^3.0.0+1
  flutter_snake_navigationbar: ^0.6.1




dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/svg/
    - assets/png/
    - assets/data/
    - assets/lottie/
    - assets/png/shop/
    - assets/png/card/
    - assets/png/temp/
    - assets/png/story/
    - assets/png/banner/
    - assets/png/product/
    - assets/png/g_movie/
    - assets/png/category/
    - assets/png/g_travel/
    - assets/svg/g_travel/
    - assets/png/g_grocery/
    - assets/png/g_medical/
    - assets/png/g_weather/
    - assets/svg/g_medical/
    - assets/data/pay_data/
    - assets/data/bike_data/
    - assets/data/cart_data/
    - assets/data/chat_data/
    - assets/png/onboarding/
    - assets/data/movie_data/
    - assets/png/bike_product/
    - assets/data/travel_data/
    - assets/data/cooking_data/
    - assets/data/medical_data/
    - assets/data/grocery_data/

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
